using FlatRedBall.Content.AnimationChain;
using System.Collections.Generic;
using System.IO;

namespace AnimChainsGenerator
{
    public sealed class Generator
    {
        private static Size _FrameSize;
        private static string _SpriteSheetFileName;
        private static ushort _Rotations;
        private static Offset<float> _AllFramesOffset;

        /// <summary>Generates AnimationChainListSave data structure based on input data.</summary>
        /// <param name="frameSize">Size of one sprite sheet cell. All cells in spritesheed have to have uniform size.</param>
        /// <param name="spriteSheetFileName">Only file name of sprite sheet that should be used for generated anim chain. Without path.</param>
        /// <param name="rotations">Number of rotations (sprite sheet rows) for graphic character/object this anim chain is generated for.</param>
        /// <param name="animsDefinitions">List of AnimDefs defining animations for graphic character/object.</param>
        /// <returns>Generated AnimationChainListSave data.</returns>
        public static AnimationChainListSave Generate(
            Size frameSize,
            string spriteSheetFileName,
            ushort rotations,
            Offset<float> allFramesOffset,
            IEnumerable<AnimDef> animsDefinitions
        )
        {
            _FrameSize = frameSize;
            _SpriteSheetFileName = spriteSheetFileName;
            _Rotations = rotations;
            _AllFramesOffset = allFramesOffset;

            AnimationChainListSave animChainListSave = new AnimationChainListSave
            {
                CoordinateType = FlatRedBall.Graphics.TextureCoordinateType.Pixel,
                FileRelativeTextures = true,
                TimeMeasurementUnit = FlatRedBall.TimeMeasurementUnit.Second
            };

            foreach (var animDef in animsDefinitions)
            {
                animChainListSave.AnimationChains.AddRange(
                    _GenerateAnimChain(animDef)
                );
            }

            return animChainListSave;
        }

        private static AnimationChainSave[] _GenerateAnimChain(AnimDef animDef)
        {
            // * frame coordinates are in pixels. top-left = 0,0  bottom-right = +X +Y

            float xStart = animDef.CellXstartIndex * _FrameSize.Width;
            float yStart = animDef.CellYstartIndex * _FrameSize.Height;

            AnimationChainSave[] animsList = new AnimationChainSave[_Rotations];

            //float currentXStart;
            float currentYTop;
            float currentYBottom;
            float left;
            AnimationChainSave oneRotAnim;
            AnimationFrameSave frame;
            for (ushort iRotation = 0; iRotation < 16; iRotation++)
            {
                currentYTop = yStart + iRotation * _FrameSize.Height;
                currentYBottom = currentYTop + _FrameSize.Height;
                oneRotAnim = new AnimationChainSave(); // animDef.FramesPerRotation
                oneRotAnim.Name = animDef.AnimName + '_' + iRotation.ToString();

                for (ushort iFrame = 0; iFrame < animDef.FramesPerRotation; iFrame++)
                {
                    left = xStart + iFrame * _FrameSize.Width;

                    frame = new AnimationFrameSave // (_FramesTexture, 0)
                    {
                        TextureName = _SpriteSheetFileName,
                        TopCoordinate = currentYTop,
                        BottomCoordinate = currentYBottom,
                        LeftCoordinate = left,
                        RightCoordinate = left + _FrameSize.Width,
                        RelativeX = _AllFramesOffset.X,
                        RelativeY = _AllFramesOffset.Y,
                        FrameLength = 0.1f
                    };

                    //oneRotAnim.Add(frame);
                    oneRotAnim.Frames.Add(frame);
                }

                //animsList.Add(oneRotAnim);
                animsList[iRotation] = oneRotAnim;
            }

            return animsList;
        }

        /// <summary>Saves generated AnimChainList to file and copies it's sprite sheet file to same director if necessary.</summary>
        /// <param name="animChainListSave">AnimationChainListSave data structure generated by GenerateAnimChain()</param>
        /// <param name="achxSavePath">Directory path to where achx file should be saved</param>
        /// <param name="achxFileName">Name of achx output file without extension</param>
        /// <param name="spriteSheetLocation">Directory where sprite sheet image for this cnim chain is located</param>
        public static void SaveAchx(AnimationChainListSave animChainListSave, string achxSavePath, string achxFileName, string spriteSheetLocation)
        {
            if ( ! File.Exists( Path.Combine(achxSavePath, _SpriteSheetFileName) ) )
            {
                File.Copy(
                    Path.Combine(spriteSheetLocation, _SpriteSheetFileName),
                    Path.Combine(achxSavePath, _SpriteSheetFileName)
                );
            }

            animChainListSave.Save( Path.Combine(achxSavePath, achxFileName + ".achx") );
        }
    }
}
